version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=shopdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
    

volumes:
  db:
    driver: local