# Generated by Django 5.1.1 on 2024-09-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
